### ISSUE TITLE
Download entire book as PDF?

### ISSUE THREAD

**Issue by RichardLitt** [protontypes/open-source-in-environmental-sustainability#14]
Is there a way to do this?

**Comment by Ly0n** [comment]
Hi @RichardLitt,
the PDF export is still under development on the side of Jupyter Book. In principle, the export works, but it does not look good. Until now, we have not been able to design the website and especially the plots in such a way that it looks representive. @joshhopkins and me actually discussed to manually redesign the PDF with the content based on a LaTeX export.

I have commited an [PDF export](https://github.com/protontypes/open-source-in-environmental-sustainability/blob/f9355f08b1458e7fb303f4a0f6644ca97e852006/open-source-in-environmental-sustainability.pdf) to the repo that was created with the following command:

```bash
jupyter-book build open-source-in-environmental-sustainability --builder pdfhtml
```

**Comment by RichardLitt** [comment]
Got it. Thanks for committing that! I'll endeavor to just read it on the website for now.
